import type { User, Order, ScrapCategory, Payment } from '@/lib/types';
import { subDays, subHours } from 'date-fns';

const now = new Date();

export const users: User[] = [
  {
    id: 'user-1',
    name: 'Anika Sharma',
    phone: '+91 9876543210',
    email: 'anika.sharma@example.com',
    role: 'seller',
    address: '123, Rose Villa, Mumbai',
    zone: 'West',
    kycStatus: 'verified',
    totalOrders: 12,
    totalWeight: 250.5,
    walletBalance: 1500.75,
    createdAt: subDays(now, 5).toISOString(),
    avatarUrl: 'https://i.pravatar.cc/150?u=anika.sharma@example.com',
  },
  {
    id: 'user-2',
    name: 'Rohan Gupta',
    phone: '+91 8765432109',
    email: 'rohan.gupta@example.com',
    role: 'agent',
    address: '456, Lily Apartments, Delhi',
    zone: 'North',
    kycStatus: 'verified',
    totalOrders: 58,
    totalWeight: 1200,
    walletBalance: 3200.0,
    createdAt: subDays(now, 10).toISOString(),
    avatarUrl: 'https://i.pravatar.cc/150?u=rohan.gupta@example.com',
    rating: 4.8,
  },
  {
    id: 'user-3',
    name: 'Priya Singh',
    phone: '+91 7654321098',
    email: 'priya.singh@example.com',
    role: 'seller',
    address: '789, Orchid Heights, Bangalore',
    zone: 'South',
    kycStatus: 'pending',
    totalOrders: 3,
    totalWeight: 45.2,
    walletBalance: 350.5,
    createdAt: subDays(now, 2).toISOString(),
    avatarUrl: 'https://i.pravatar.cc/150?u=priya.singh@example.com',
  },
  {
    id: 'user-4',
    name: 'Amit Patel',
    phone: '+91 6543210987',
    email: 'amit.patel@example.com',
    role: 'agent',
    address: '101, Sunstone Park, Ahmedabad',
    zone: 'West',
    kycStatus: 'verified',
    totalOrders: 75,
    totalWeight: 1800,
    walletBalance: 4500.0,
    createdAt: subDays(now, 25).toISOString(),
    avatarUrl: 'https://i.pravatar.cc/150?u=amit.patel@example.com',
    rating: 4.9,
  },
  {
    id: 'user-5',
    name: 'Sonia Reddy',
    phone: '+91 5432109876',
    email: 'sonia.reddy@example.com',
    role: 'buyer',
    address: '202, Silicon Towers, Hyderabad',
    zone: 'South',
    kycStatus: 'verified',
    totalOrders: 200,
    totalWeight: 5000,
    walletBalance: 0,
    createdAt: subDays(now, 40).toISOString(),
    avatarUrl: 'https://i.pravatar.cc/150?u=sonia.reddy@example.com',
  },
  {
    id: 'user-6',
    name: 'Vikram Bose',
    phone: '+91 4321098765',
    email: 'vikram.bose@example.com',
    role: 'admin',
    address: 'Admin HQ, Kolkata',
    zone: 'East',
    kycStatus: 'verified',
    totalOrders: 0,
    totalWeight: 0,
    walletBalance: 0,
    createdAt: subDays(now, 100).toISOString(),
    avatarUrl: 'https://i.pravatar.cc/150?u=vikram.bose@example.com',
  },
];

export const scrapCategories: ScrapCategory[] = [
  { id: 'cat-1', name: 'Steel', pricePerKg: 25, updatedAt: now.toISOString() },
  { id: 'cat-2', name: 'Aluminum', pricePerKg: 120, updatedAt: now.toISOString() },
  { id: 'cat-3', name: 'Copper', pricePerKg: 450, updatedAt: subDays(now, 1).toISOString() },
  { id: 'cat-4', name: 'Plastic', pricePerKg: 15, updatedAt: subDays(now, 2).toISOString() },
  { id: 'cat-5', name: 'Paper', pricePerKg: 10, updatedAt: now.toISOString() },
];

export const orders: Order[] = [
  {
    id: 'order-101',
    sellerId: 'user-1',
    agentId: 'user-2',
    scrapCategory: 'Steel',
    estimatedWeight: 20,
    finalWeight: 22.5,
    pricePerKg: 25,
    totalAmount: 562.5,
    pickupAddress: '123, Rose Villa, Mumbai',
    pickupTime: subHours(now, 2).toISOString(),
    status: 'completed',
    createdAt: subHours(now, 4).toISOString(),
  },
  {
    id: 'order-102',
    sellerId: 'user-3',
    agentId: 'user-4',
    scrapCategory: 'Plastic',
    estimatedWeight: 15,
    pickupAddress: '789, Orchid Heights, Bangalore',
    pickupTime: new Date().toISOString(),
    status: 'assigned',
    pricePerKg: 15,
    createdAt: subDays(now, 1).toISOString(),
  },
  {
    id: 'order-103',
    sellerId: 'user-1',
    scrapCategory: 'Aluminum',
    estimatedWeight: 5,
    pricePerKg: 120,
    pickupAddress: '123, Rose Villa, Mumbai',
    pickupTime: subDays(now, 2).toISOString(),
    status: 'pending',
    createdAt: subDays(now, 1).toISOString(),
  },
  {
    id: 'order-104',
    sellerId: 'user-1',
    agentId: 'user-2',
    scrapCategory: 'Copper',
    estimatedWeight: 2,
    finalWeight: 1.8,
    pricePerKg: 450,
    totalAmount: 810,
    pickupAddress: '123, Rose Villa, Mumbai',
    pickupTime: subDays(now, 3).toISOString(),
    status: 'completed',
    createdAt: subDays(now, 3).toISOString(),
  },
  {
    id: 'order-105',
    sellerId: 'user-3',
    agentId: 'user-4',
    scrapCategory: 'Paper',
    estimatedWeight: 30,
    pickupAddress: '789, Orchid Heights, Bangalore',
    pickupTime: subHours(now, 5).toISOString(),
    status: 'on_the_way',
    pricePerKg: 10,
    createdAt: subHours(now, 6).toISOString(),
  },
  {
    id: 'order-106',
    sellerId: 'user-5',
    scrapCategory: 'Steel',
    estimatedWeight: 500,
    pricePerKg: 25,
    pickupAddress: '202, Silicon Towers, Hyderabad',
    pickupTime: subDays(now, 4).toISOString(),
    status: 'cancelled',
    createdAt: subDays(now, 4).toISOString(),
  },
];

export const payments: Payment[] = [
    { id: 'pay-1', userId: 'user-1', orderId: 'order-101', amount: 562.5, type: 'sellerPayout', paymentMode: 'UPI', status: 'completed', createdAt: subHours(now, 1).toISOString() },
    { id: 'pay-2', userId: 'user-2', orderId: 'order-101', amount: 50, type: 'agentPayout', paymentMode: 'bank', status: 'completed', createdAt: subHours(now, 1).toISOString() },
    { id: 'pay-3', userId: 'user-1', orderId: 'order-104', amount: 810, type: 'sellerPayout', paymentMode: 'UPI', status: 'completed', createdAt: subDays(now, 2).toISOString() },
    { id: 'pay-4', userId: 'user-4', orderId: 'order-102', amount: 30, type: 'agentPayout', paymentMode: 'bank', status: 'pending', createdAt: subDays(now, 1).toISOString() }
];

export function getSellerById(id: string) {
    return users.find(u => u.id === id && u.role === 'seller');
}

export function getAgentById(id: string) {
    return users.find(u => u.id === id && u.role === 'agent');
}
